title: "David Gerth"
author: ""
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Blog", file: "blog.md"}
  - {title: "Resume", url: "https://github.com/dgerth5/dgerth5.github.io/blob/master/David_Gerth_Resume_2025.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:davidgerth5@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/dgerth5"}
  - {title: Twitter, icon: twitter, url: "https://x.com/dgerth1305"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
mathjax: true
